paths:
  /accounts/{ACCOUNT_ID}/security:
    delete:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Delete an instance of security
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets all security
    patch:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../oas3-schemas.yml#/security'
      responses:
        200:
          description: Successful operation
      summary: Patch specific fields of security
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../oas3-schemas.yml#/security'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of security
  /accounts/{ACCOUNT_ID}/security/attempts:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets attempts of security
  /accounts/{ACCOUNT_ID}/security/attempts/{ATTEMPT_ID}:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ATTEMPT_ID'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets a security by ID
